// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFsDFUpcDBq4ourF_yCvT1U16jFkqmb6k',
    appId: '1:439449022486:web:390d9d6543f15aa9a40537',
    messagingSenderId: '439449022486',
    projectId: 'logntest-ac299',
    authDomain: 'logntest-ac299.firebaseapp.com',
    storageBucket: 'logntest-ac299.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk_jSulV-pGjmllQb_4zzreHPw7Ps503M',
    appId: '1:439449022486:android:3eee94b554042267a40537',
    messagingSenderId: '439449022486',
    projectId: 'logntest-ac299',
    storageBucket: 'logntest-ac299.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClVQ25LdSqQAQdcXr9q2pQkl4QGk_GC_A',
    appId: '1:439449022486:ios:924e0007e9310392a40537',
    messagingSenderId: '439449022486',
    projectId: 'logntest-ac299',
    storageBucket: 'logntest-ac299.appspot.com',
    iosBundleId: 'com.example.loginTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClVQ25LdSqQAQdcXr9q2pQkl4QGk_GC_A',
    appId: '1:439449022486:ios:349ea9b6a9991cd2a40537',
    messagingSenderId: '439449022486',
    projectId: 'logntest-ac299',
    storageBucket: 'logntest-ac299.appspot.com',
    iosBundleId: 'com.example.loginTest.RunnerTests',
  );
}
